### ISSUE TITLE
image example doesnt compile

### ISSUE THREAD

**Issue by aep** [kennytm/qrcode-rust#19]
```rust
extern crate image;
extern crate qrcode;

use qrcode::QrCode;
use image::Luma;

fn main() {
    // Encode some data into bits.
    let code = QrCode::new(b"01234567").unwrap();

    // Render the bits into an image.
    let image = code.render::<Luma<u8>>().build();

    // Save the image.
    image.save("/tmp/qrcode.png").unwrap();
}
```

```
error[E0277]: the trait bound `image::Luma<u8>: qrcode::render::string::Element` is not satisfied
  --> src/main.rs:12:22
   |
12 |     let image = code.render::<Luma<u8>>().build();
   |                      ^^^^^^ the trait `qrcode::render::string::Element` is not implemented for `image::Luma<u8>`
   |
   = note: required because of the requirements on the impl of `qrcode::render::Pixel` for `image::Luma<u8>`

error[E0599]: no method named `build` found for type `qrcode::render::Renderer<'_, image::Luma<u8>>` in the current scope
  --> src/main.rs:12:43
   |
12 |     let image = code.render::<Luma<u8>>().build();
   |                                           ^^^^^
   |
   = note: the method `build` exists but the following trait bounds were not satisfied:
           `image::Luma<u8> : qrcode::render::Pixel`

error: aborting due to 2 previous errors

error: Could not compile `factory`.

To learn more, run the command again with --verbose.

```

**Comment by ritiek** [comment]
Looks like the `image` crate made some backward incompatible changes as of `v0.18.0` and broke the API. It compiles OK with `image = "0.17.0"`.

**Comment by kennytm** [comment]
No repro for me. Could you check your `Cargo.toml`? Note that `qrcode 0.6.0` requires `image 0.18.*`, it can't be used if you're using other versions of `image`.

**Comment by jomag** [comment]
Any progress on this? I have the same problem.

- qrcode 0.11.2
- image 0.23.14

**Comment by gordon-quad** [comment]
same issue with

- qrcode 0.12.0
- image 0.24.0

**Comment by matthiasdebernardini** [comment]
I am also having this issue with 
qrcode = "0.12.0"
image = "0.24.2"

**Comment by fc7** [comment]
It only works with image 0.23.x, as already mentioned [here](https://github.com/kennytm/qrcode-rust/issues/56#issuecomment-1106204564).

**Comment by hujuu** [comment]
I faced the same issue.

However, I was able to generate it with the following settings.

```
qrcode = "0.12.0"
image = "0.23.14"
```

**Comment by b1ek** [comment]
Same thing.

```
image = "0.24.7"
qrcode = "0.12.0"
```

**Comment by dravenk** [comment]
same.
```
qrcode = { version = "0.12.0", default-features = false }
image = "0.24.7"
```
