### ISSUE TITLE
Example doesn't work with image 0.12+

### ISSUE THREAD

**Issue by skinkade** [kennytm/qrcode-rust#11]
Building the example in the README yields an error if in Cargo.toml you're using a recent `image` release:

```rust
error[E0308]: mismatched types
  --> src/main.rs:12:28
   |
12 |     let image: GrayImage = code.render().to_image();
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `image::ImageBuffer`, found struct `image::buffer::ImageBuffer`
   |
   = note: expected type `image::ImageBuffer<image::Luma<u8>, std::vec::Vec<u8>>`
   = note:    found type `image::buffer::ImageBuffer<_, std::vec::Vec<_>>`
```

**Comment by kennytm** [comment]
I guess this is simply because qrcode 0.2.0 was depending on image 0.10. I have published [qrcode 0.2.1](https://crates.io/crates/qrcode) which depends on image 0.12 now, and the example compiles fine.
